[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt',
    'playwright install chromium',
    'playwright install-deps chromium'
]

[start]
cmd = 'python db_postgres.py'
